version: "3"
services:
    test_web:
        image: nginx
        ports:
          - 3000:3000
        volumes:
          - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
          - test_application

    test_database:
        image: mysql:8.0
        environment:
          MYSQL_DATABASE: tjlee
          MYSQL_ROOT_PASSWORD: q1w2e3Q!W@E#
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306

    test_application:
        build: .
        expose:
          - 8080
        depends_on:
          - test_database
